const MODAL_PAGE_TABLE_OPTIONS = 'table_options'
// const MODAL_PAGE_TABLE_TYPE = 'table_type'
const MODAL_PAGE_TABLE_VARIANT = 'table_variant'
const MODAL_PAGE_TABLE_MODE = 'table_mode'
// const MODAL_PAGE_TABLE_COLOR = 'table_color'
// const MODAL_PAGE_TABLE_RED_BLACK_VARIANT = 'table_red_black_variant'
const MODAL_PAGE_TABLE_SIZE = 'table_size'
const MODAL_PAGE_TABLE_SEQUENCE = 'table_sequence'
const MODAL_PAGE_TABLE_TRANSFORMS = 'table_transforms'

export const MODAL_PAGES = {
   TABLE_OPTIONS: MODAL_PAGE_TABLE_OPTIONS,
   // TABLE_TYPE: MODAL_PAGE_TABLE_TYPE,
   TABLE_VARIANT: MODAL_PAGE_TABLE_VARIANT,
   TABLE_MODE: MODAL_PAGE_TABLE_MODE,
   TABLE_SIZE: MODAL_PAGE_TABLE_SIZE,
   // TABLE_COLOR: MODAL_PAGE_TABLE_COLOR,
   // TABLE_RED_BLACK_VARIANT: MODAL_PAGE_TABLE_RED_BLACK_VARIANT,
   TABLE_SEQUENCE: MODAL_PAGE_TABLE_SEQUENCE,
   TABLE_TRANSFORMS: MODAL_PAGE_TABLE_TRANSFORMS,
} as const
