const MODAL_PAGE_TABLE_PARAMS = 'table_params'
const MODAL_PAGE_TABLE_TYPE = 'table_type'
const MODAL_PAGE_TABLE_VARIANT = 'table_variant'
const MODAL_PAGE_TABLE_MODE = 'table_mode'
const MODAL_PAGE_TABLE_SIZE = 'table_size'
const MODAL_PAGE_TABLE_SEQUENCE = 'table_sequence'

export const MODAL_PAGES = {
   TABLE_PARAMS: MODAL_PAGE_TABLE_PARAMS,
   TABLE_TYPE: MODAL_PAGE_TABLE_TYPE,
   TABLE_VARIANT: MODAL_PAGE_TABLE_VARIANT,
   TABLE_MODE: MODAL_PAGE_TABLE_MODE,
   TABLE_SIZE: MODAL_PAGE_TABLE_SIZE,
   TABLE_SEQUENCE: MODAL_PAGE_TABLE_SEQUENCE,
}
