const ACTION_SHEET_TABLE_SIZE = 'action_sheet_table_size'
const ACTION_SHEET_TABLE_SEQUENCE = 'action_sheet_table_sequence'
const ACTION_SHEET_TABLE_STYLE_SELECTED = 'action_sheet_table_style_selected'

export const POPUPS = {
   ACTION_SHEET_TABLE_SIZE: ACTION_SHEET_TABLE_SIZE,
   ACTION_SHEET_TABLE_SEQUENCE: ACTION_SHEET_TABLE_SEQUENCE,
   ACTION_SHEET_TABLE_STYLE_SELECTED: ACTION_SHEET_TABLE_STYLE_SELECTED,
}
